name = "cordgift-rickroll"
type = "webpack"
route = 'dis.cord.gift/*'
zone_id = '3a9f3141926f0eed9ce9d1bc4b1f758e'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = false
compatibility_date = "2021-11-18"

webpack_config = "webpack.config.js"

# account_id is required if you have multiple accounts within single profile.
# account_id = ""

[site]
bucket = "./public" # <-- Add your build directory name here!
entry-point = "."
